name: Dependency Scan

on:
  workflow_dispatch:
  
jobs:
  scan-repositories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install jq
      
      - name: Debug Repository
        run: |
          pwd
          ls -al
          git status

      - name: Scan for Dependency
        id: scan
        run: |
          REPO_NAME=$(basename $(pwd))
          echo "Current repository: $REPO_NAME"
          POM_URL_ROOT="https://api.github.com/repos/lokeshorg/${REPO_NAME}/contents/pom.xml"
          echo "POM URL: $POM_URL_ROOT"
          RESPONSE=$(curl -s -H "Authorization: Bearer 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" "$POM_URL_ROOT")
          echo "Response: $RESPONSE"
          content=$(echo "$RESPONSE" | jq -r '.content')
          echo "Content: $content"
          decoded_content=$(echo "$content" | base64 --decode)
          echo "Decoded Content: $decoded_content"
          if grep -q '<junit.version>4.12</junit.version>' <<< "$decoded_content"; then
            echo "Repository with junit.version 4.12 found: $REPO_NAME"
            echo "::set-output name=repos::$REPO_NAME"
          else
            echo "Repository does not contain junit.version 4.12: $REPO_NAME"
          fi

      - name: Output Results
        if: steps.scan.outputs.repos != ''
        run: |
          echo "Repositories with junit.version 4.12: ${{ steps.scan.outputs.repos }}"
