name: pom.xml version determine
on:
  push:
    branches:
      - main

jobs:
  pom-finds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Perform REST API request
        env:
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        run: |
          ORG_NAME="lokeshorg"

          check_pom_content() {
              local REPO_NAME="$1"
              local POM_URL="$2"
              RESPONSE=$(curl -s -H "Authorization: Bearer $BEARER_TOKEN" "$POM_URL")
              content=$(echo "$RESPONSE" | jq -r '.content')
              decoded_content=$(echo "$content" | base64 --decode)
              if grep -q '<junit.version>4.12</junit.version>' <<< "$decoded_content"; then
                  echo "Repository with junit.version 4.12 found: $REPO_NAME"
              fi
          }

          REPOS_URL="https://api.github.com/orgs/${ORG_NAME}/repos"
          REPO_RESPONSE=$(curl -s -H "Authorization: Bearer $BEARER_TOKEN" "$REPOS_URL")
          REPO_NAMES=$(echo "$REPO_RESPONSE" | jq -r '.[].name')
          
          for REPO_NAME in $REPO_NAMES; do
              POM_URL_ROOT="https://api.github.com/repos/${ORG_NAME}/${REPO_NAME}/contents/pom.xml"
              check_pom_content "$REPO_NAME" "$POM_URL_ROOT"
              POM_URL_MULEBOM="https://api.github.com/repos/${ORG_NAME}/${REPO_NAME}/contents/mulebom/pom.xml"
              check_pom_content "$REPO_NAME" "$POM_URL_MULEBOM"
          done
