name: Dependency Scan

on:
  workflow_dispatch:
  
jobs:
  scan-repositories:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Install jq
        run: sudo apt-get install jq
      
      - name: List Repositories
        id: list-repos
        run: |
          ORG_NAME="${{ secrets.ORG_NAME }}"
          REPOS_URL="https://api.github.com/orgs/${ORG_NAME}/repos"
          RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "${REPOS_URL}")
          echo "Response: $RESPONSE"
          REPO_NAMES=$(echo "$RESPONSE" | jq -r '.[] | .name')
          echo "::set-output name=repos::$REPO_NAMES"

      - name: Scan for Dependency
        id: scan
        run: |
          DEPENDENCY_VERSION="${{ secrets.DEPENDENCY_VERSION }}"
          for REPO_NAME in ${{ steps.list-repos.outputs.repos }}; do
            echo "Scanning repository: $REPO_NAME"
            POM_URL_ROOT="https://api.github.com/repos/${ORG_NAME}/${REPO_NAME}/contents/pom.xml"
            RESPONSE=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "$POM_URL_ROOT")
            content=$(echo "$RESPONSE" | jq -r '.content')
            decoded_content=$(echo "$content" | base64 --decode)
            if grep -q "<junit.version>${DEPENDENCY_VERSION}</junit.version>" <<< "$decoded_content"; then
              echo "Repository with junit.version ${DEPENDENCY_VERSION} found: $REPO_NAME"
              echo "::set-output name=repos::$REPO_NAME"
            fi
          done

      - name: Output Results
        if: steps.scan.outputs.repos != ''
        run: |
          echo "Repositories with junit.version ${DEPENDENCY_VERSION}: ${{ steps.scan.outputs.repos }}"
      - name: No Results Found
        if: steps.scan.outputs.repos == ''
        run: echo "No repositories with junit.version ${DEPENDENCY_VERSION} found."
